//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool.Desktop
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Windows.Media.Imaging;

    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.EmployeeServices = new HashSet<EmployeeService>();
            this.SalesHistories = new HashSet<SalesHistory>();
            this.ServicePhotoes = new HashSet<ServicePhoto>();
            this.SignUpServices = new HashSet<SignUpService>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string GenderRecomented { get; set; }
        public string Description { get; set; }
        public string Cost { get; set; }
        public Nullable<int> Sale { get; set; }
        public string Duration { get; set; }
        public string MainPhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeService> EmployeeServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesHistory> SalesHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePhoto> ServicePhotoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SignUpService> SignUpServices { get; set; }

        [NotMapped]
        public string CostByDuration => $"{Cost} рублей за {Duration} минут.";

        [NotMapped]
        public string SaleString => Sale > 0 ? $"* скидка {Sale} %" : string.Empty;

        [NotMapped]
        public BitmapImage ServicesPhotoFromResources => !string.IsNullOrEmpty(MainPhoto)
            ? new BitmapImage(new Uri(System.IO.Directory.GetCurrentDirectory().Replace("\\bin\\Debug", string.Empty).Replace("\\", "/") + "/" +  MainPhoto.Replace("\\", "/").TrimStart(' ')))
                : new BitmapImage(new Uri(System.IO.Directory.GetCurrentDirectory().Replace("\\bin\\Debug", string.Empty).Replace("\\", "/") + "/Photos/picture.png"));
    }
}
